# Generated by Django 2.2 on 2020-08-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200412_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
